#!/usr/bin/env bash
# Process Loop (better than forever)
# Usage:
#
#   ./loop echo or any bash command
#
#  Ctrl+C Restarts
#  Ctrl+\ Quits
#

ctrl_c() {
  echo -en "\n\n*** Restarting ***\n\n"
}

ctrl_backslash() {
  echo -en "\n\n*** Killing ***\n\n"
  exit 0
}

# trap keyboard interrupt
trap ctrl_c SIGINT
trap ctrl_backslash SIGQUIT

# the loop
reset; while true; do $*; done
